name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up JDK 21
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    # Assemble the project with Gradle Wrapper to jar file
    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build jar using Gradle
      run: ./gradlew build

    # Login to Docker Hub
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    # Build Docker image
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest .

    # Push Docker image
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest

    # SSH into EC2 instance and deploy
    - name: SSH into EC2 instance and deploy Docker container
      run: |
        echo "${{ secrets.EC2_PRIVATE_KEY }}" > private_key.pem
        chmod 600 private_key.pem
        ssh -o StrictHostKeyChecking=no -i private_key.pem -p ${{ secrets.EC2_SSH_PORT }} ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest
          docker stop myapp || true
          docker rm myapp || true
          docker run -d --name myapp -p 80:8080 ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest
        EOF
